name: enguide_app
description: "Enguide: English learn & example application."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# projeye dahil edilen tum paketler
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # responsive ui package
  flutter_screenutil:
  # data loading animation package
  shimmer: ^3.0.0
  # restfull api and internet control packages
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.6
  # country icons
  country_flags: ^2.2.0
  # flutter image packages
  flutter_svg: ^2.0.9
  # animated packages
  lottie: ^3.0.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  awesome_snackbar_content: ^0.1.3
  # input field
  searchfield: ^0.9.0
  pinput: ^4.0.0
  # utility packages
  email_validator: ^2.1.17
  # state management packages
  provider: ^6.1.1
  # Localization - multi language package
  easy_localization: ^3.0.4
  # application safety
  flutter_dotenv: ^5.1.0
  aescryptojs: ^1.0.0
  jwt_decoder: ^2.0.1
  # cache  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # device path
  path_provider: ^2.1.3

# "Gelistirme surecinde" projeye dahil edilen tum paketler
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true


# projeye dahil edilen gorsel,video,gif,font araclari
  assets:
    - lib/assets/images/logo/
    - lib/assets/images/svg/
    - lib/assets/images/gif/
    - lib/assets/l10n/
    - lib/assets/.env
    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
